# Use a specific version tag for better reproducibility
FROM redhat/ubi9-micro:9.5-1733126338@sha256:a410623c2b8e9429f9606af821be0231fef2372bd0f5f853fbe9743a0ddf7b34

# Copy the binary to the appropriate directory
COPY bin/controller /usr/bin/terrapi-controller

# Ensure the binary has execute permissions
RUN chmod +x /usr/bin/terrapi-controller

# Set the entrypoint
ENTRYPOINT ["/usr/bin/terrapi-controller"]