# Use a specific version tag for better reproducibility
FROM redhat/ubi9-micro:9.5-1733767087@sha256:111395a0b54d220c4ad821602a4a28807d6c4fb2feb19b43a6468a9d5f257463

# Copy the binary to the appropriate directory
COPY bin/controller /usr/bin/terrapi-controller

# Ensure the binary has execute permissions
RUN chmod +x /usr/bin/terrapi-controller

# Set the entrypoint
ENTRYPOINT ["/usr/bin/terrapi-controller"]