# Use a specific version tag for better reproducibility
FROM redhat/ubi9-micro:9.5-1734513256@sha256:becdf7fff4509ee81df982000d0adef858a7ae7995dfb7d774b9ded6a461ebad

# Copy the binary to the appropriate directory
COPY bin/controller /usr/bin/terrapi-controller

# Ensure the binary has execute permissions
RUN chmod +x /usr/bin/terrapi-controller

# Set the entrypoint
ENTRYPOINT ["/usr/bin/terrapi-controller"]