// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v5.28.2
// source: api/deployment.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeploymentRequest_Action int32

const (
	DeploymentRequest_init    DeploymentRequest_Action = 0
	DeploymentRequest_plan    DeploymentRequest_Action = 1
	DeploymentRequest_apply   DeploymentRequest_Action = 2
	DeploymentRequest_destroy DeploymentRequest_Action = 3
)

// Enum value maps for DeploymentRequest_Action.
var (
	DeploymentRequest_Action_name = map[int32]string{
		0: "init",
		1: "plan",
		2: "apply",
		3: "destroy",
	}
	DeploymentRequest_Action_value = map[string]int32{
		"init":    0,
		"plan":    1,
		"apply":   2,
		"destroy": 3,
	}
)

func (x DeploymentRequest_Action) Enum() *DeploymentRequest_Action {
	p := new(DeploymentRequest_Action)
	*p = x
	return p
}

func (x DeploymentRequest_Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeploymentRequest_Action) Descriptor() protoreflect.EnumDescriptor {
	return file_api_deployment_proto_enumTypes[0].Descriptor()
}

func (DeploymentRequest_Action) Type() protoreflect.EnumType {
	return &file_api_deployment_proto_enumTypes[0]
}

func (x DeploymentRequest_Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeploymentRequest_Action.Descriptor instead.
func (DeploymentRequest_Action) EnumDescriptor() ([]byte, []int) {
	return file_api_deployment_proto_rawDescGZIP(), []int{2, 0}
}

type RetrieveDeploymentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *RetrieveDeploymentRequest) Reset() {
	*x = RetrieveDeploymentRequest{}
	mi := &file_api_deployment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrieveDeploymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveDeploymentRequest) ProtoMessage() {}

func (x *RetrieveDeploymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_deployment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveDeploymentRequest.ProtoReflect.Descriptor instead.
func (*RetrieveDeploymentRequest) Descriptor() ([]byte, []int) {
	return file_api_deployment_proto_rawDescGZIP(), []int{0}
}

func (x *RetrieveDeploymentRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeploymentModule struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Address  string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Path     string `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Username string `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	Password string `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *DeploymentModule) Reset() {
	*x = DeploymentModule{}
	mi := &file_api_deployment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeploymentModule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeploymentModule) ProtoMessage() {}

func (x *DeploymentModule) ProtoReflect() protoreflect.Message {
	mi := &file_api_deployment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeploymentModule.ProtoReflect.Descriptor instead.
func (*DeploymentModule) Descriptor() ([]byte, []int) {
	return file_api_deployment_proto_rawDescGZIP(), []int{1}
}

func (x *DeploymentModule) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeploymentModule) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *DeploymentModule) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *DeploymentModule) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *DeploymentModule) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type DeploymentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Action    DeploymentRequest_Action     `protobuf:"varint,1,opt,name=action,proto3,enum=api.DeploymentRequest_Action" json:"action,omitempty"`
	Variables []*DeploymentRequestVariable `protobuf:"bytes,2,rep,name=variables,proto3" json:"variables,omitempty"`
}

func (x *DeploymentRequest) Reset() {
	*x = DeploymentRequest{}
	mi := &file_api_deployment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeploymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeploymentRequest) ProtoMessage() {}

func (x *DeploymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_deployment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeploymentRequest.ProtoReflect.Descriptor instead.
func (*DeploymentRequest) Descriptor() ([]byte, []int) {
	return file_api_deployment_proto_rawDescGZIP(), []int{2}
}

func (x *DeploymentRequest) GetAction() DeploymentRequest_Action {
	if x != nil {
		return x.Action
	}
	return DeploymentRequest_init
}

func (x *DeploymentRequest) GetVariables() []*DeploymentRequestVariable {
	if x != nil {
		return x.Variables
	}
	return nil
}

type DeploymentRequestVariable struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value  string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Secret bool   `protobuf:"varint,3,opt,name=secret,proto3" json:"secret,omitempty"`
}

func (x *DeploymentRequestVariable) Reset() {
	*x = DeploymentRequestVariable{}
	mi := &file_api_deployment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeploymentRequestVariable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeploymentRequestVariable) ProtoMessage() {}

func (x *DeploymentRequestVariable) ProtoReflect() protoreflect.Message {
	mi := &file_api_deployment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeploymentRequestVariable.ProtoReflect.Descriptor instead.
func (*DeploymentRequestVariable) Descriptor() ([]byte, []int) {
	return file_api_deployment_proto_rawDescGZIP(), []int{3}
}

func (x *DeploymentRequestVariable) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeploymentRequestVariable) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *DeploymentRequestVariable) GetSecret() bool {
	if x != nil {
		return x.Secret
	}
	return false
}

type Deployment struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Module  *DeploymentModule  `protobuf:"bytes,1,opt,name=module,proto3" json:"module,omitempty"`
	Request *DeploymentRequest `protobuf:"bytes,2,opt,name=request,proto3" json:"request,omitempty"`
}

func (x *Deployment) Reset() {
	*x = Deployment{}
	mi := &file_api_deployment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Deployment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Deployment) ProtoMessage() {}

func (x *Deployment) ProtoReflect() protoreflect.Message {
	mi := &file_api_deployment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Deployment.ProtoReflect.Descriptor instead.
func (*Deployment) Descriptor() ([]byte, []int) {
	return file_api_deployment_proto_rawDescGZIP(), []int{4}
}

func (x *Deployment) GetModule() *DeploymentModule {
	if x != nil {
		return x.Module
	}
	return nil
}

func (x *Deployment) GetRequest() *DeploymentRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

var File_api_deployment_proto protoreflect.FileDescriptor

var file_api_deployment_proto_rawDesc = []byte{
	0x0a, 0x14, 0x61, 0x70, 0x69, 0x2f, 0x64, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x61, 0x70, 0x69, 0x22, 0x2b, 0x0a, 0x19, 0x52,
	0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x65, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x8c, 0x01, 0x0a, 0x10, 0x44, 0x65, 0x70,
	0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x70,
	0x61, 0x74, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12,
	0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70,
	0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70,
	0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0xbe, 0x01, 0x0a, 0x11, 0x44, 0x65, 0x70, 0x6c,
	0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x35, 0x0a,
	0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1d, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x06, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x3c, 0x0a, 0x09, 0x76, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65,
	0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x65,
	0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x56,
	0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x09, 0x76, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c,
	0x65, 0x73, 0x22, 0x34, 0x0a, 0x06, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x08, 0x0a, 0x04,
	0x69, 0x6e, 0x69, 0x74, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x70, 0x6c, 0x61, 0x6e, 0x10, 0x01,
	0x12, 0x09, 0x0a, 0x05, 0x61, 0x70, 0x70, 0x6c, 0x79, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x64,
	0x65, 0x73, 0x74, 0x72, 0x6f, 0x79, 0x10, 0x03, 0x22, 0x5d, 0x0a, 0x19, 0x44, 0x65, 0x70, 0x6c,
	0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x56, 0x61, 0x72,
	0x69, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x06, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x22, 0x6d, 0x0a, 0x0a, 0x44, 0x65, 0x70, 0x6c, 0x6f,
	0x79, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x2d, 0x0a, 0x06, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x65, 0x70, 0x6c,
	0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x52, 0x06, 0x6d, 0x6f,
	0x64, 0x75, 0x6c, 0x65, 0x12, 0x30, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x65, 0x70, 0x6c,
	0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x07, 0x72,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x32, 0x57, 0x0a, 0x11, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79,
	0x6d, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x42, 0x0a, 0x0d, 0x47,
	0x65, 0x74, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x1e, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x65, 0x44, 0x65, 0x70, 0x6c, 0x6f,
	0x79, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0f, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0x00, 0x42,
	0x31, 0x5a, 0x2f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x68,
	0x6f, 0x6d, 0x61, 0x73, 0x2d, 0x69, 0x6c, 0x6c, 0x69, 0x65, 0x74, 0x2f, 0x74, 0x65, 0x72, 0x72,
	0x61, 0x70, 0x69, 0x2d, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x2f, 0x61,
	0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_deployment_proto_rawDescOnce sync.Once
	file_api_deployment_proto_rawDescData = file_api_deployment_proto_rawDesc
)

func file_api_deployment_proto_rawDescGZIP() []byte {
	file_api_deployment_proto_rawDescOnce.Do(func() {
		file_api_deployment_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_deployment_proto_rawDescData)
	})
	return file_api_deployment_proto_rawDescData
}

var file_api_deployment_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_deployment_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_deployment_proto_goTypes = []any{
	(DeploymentRequest_Action)(0),     // 0: api.DeploymentRequest.Action
	(*RetrieveDeploymentRequest)(nil), // 1: api.RetrieveDeploymentRequest
	(*DeploymentModule)(nil),          // 2: api.DeploymentModule
	(*DeploymentRequest)(nil),         // 3: api.DeploymentRequest
	(*DeploymentRequestVariable)(nil), // 4: api.DeploymentRequestVariable
	(*Deployment)(nil),                // 5: api.Deployment
}
var file_api_deployment_proto_depIdxs = []int32{
	0, // 0: api.DeploymentRequest.action:type_name -> api.DeploymentRequest.Action
	4, // 1: api.DeploymentRequest.variables:type_name -> api.DeploymentRequestVariable
	2, // 2: api.Deployment.module:type_name -> api.DeploymentModule
	3, // 3: api.Deployment.request:type_name -> api.DeploymentRequest
	1, // 4: api.DeploymentService.GetDeployment:input_type -> api.RetrieveDeploymentRequest
	5, // 5: api.DeploymentService.GetDeployment:output_type -> api.Deployment
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_deployment_proto_init() }
func file_api_deployment_proto_init() {
	if File_api_deployment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_deployment_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_deployment_proto_goTypes,
		DependencyIndexes: file_api_deployment_proto_depIdxs,
		EnumInfos:         file_api_deployment_proto_enumTypes,
		MessageInfos:      file_api_deployment_proto_msgTypes,
	}.Build()
	File_api_deployment_proto = out.File
	file_api_deployment_proto_rawDesc = nil
	file_api_deployment_proto_goTypes = nil
	file_api_deployment_proto_depIdxs = nil
}
