---
name: binaries

"on":
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  binaries:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        id: source
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        
      - name: Setup golang
        id: golang
        uses: actions/setup-go@v5
        with:
          go-version: ^1.23.0

      - name: Run generate
        id: generate
        run: make generate

      - name: Run release
        id: release
        run: make release

      - name: Show artifacts
        id: show
        run: ls -lsa dist/

      - name: Upload release
        id: upload
        if: startsWith(github.ref, 'refs/tags/')
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GIT_TOKEN }}
          body: ${{ steps.changelog.outputs.generated }}
          artifacts: dist/*
...
